apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: dvcdsys/examples:grpcbalancing
          name: server
          command: [ "/app/bin/server" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
#      imagePullSecrets:
#        - name: regcred